# Generated by Django 2.1.3 on 2018-11-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_student'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(verbose_name='Zdobyte punkty')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Exercise', verbose_name='Zadanie')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Zadanie zrobione przez studenta',
                'verbose_name_plural': 'Zadania zrobione przez studentów',
            },
        ),
    ]
